version: '2.4'
services:
  nginx:
    container_name: dev-sidecar-nginx
    image: docmirror/dev-sidecar-nginx:1.3.0
    restart: always
    ports:
    - 443:443
    volumes:
    -  ~/deploy/ds-nginx/ssl:/app/ssl/  # 证书目录映射，不用动
    environment:
    - TZ=Asia/Shanghai
    - SSL_CERTIFICATE=/app/ssl/cert.crt # 这里修改为 /app/ssl/你的证书名称
    - SSL_CERTIFICATE_KEY=/app/ssl/cert.key # 这里修改为 /app/ssl/你的证书私钥名称
    - HOSTNAME=tocmcc.cn # 修改为你的域名
    - CONTEXT_PATH= # 路径，随便乱输入就行
    - PASSWORD= # 密码