
name: debugger-action
on:
  # push:
  #   branches:
  #     - aws-pipeline-test
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js [14.x]
       uses: actions/setup-node@v1
       with:
         node-version: 14.x

     - name: Docker yuancheng
       run: |
          	docker run -itd --network=host --cap-add NET_ADMIN --device=/dev/net/tun:/dev/net/tun --name fast -e AUTH_KEY=229e755f-dcbd-43c2-803b-eda13da56a9d yjsh14z/fastnat_linux_x64:lastest
     - name: Docker run nginx
       run: |
          cd work
          npm i
          npm run start
     - name: Setup Debug Session
       uses: csexton/debugger-action@master